package co.diseno.interfaces.vistas;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import co.diseno.interfaces.controladores.PrincipalControlador;
import co.diseno.interfaces.modelos.Dispositivo;

/**
 *
 * @author Gabriel.
 */
public class DispositivoListarFrame extends javax.swing.JInternalFrame {
    
    private PrincipalControlador principalControlador;

    /**
     * Creates new form DispositivoListarFrame
     * @param principalControlador Controlador principal.
     */
    public DispositivoListarFrame(PrincipalControlador principalControlador) {
        initComponents();
        
        this.principalControlador = principalControlador;
        mostrarDispositivos();
    }

    private void mostrarDispositivos() {
        List<Dispositivo> dispositivos = principalControlador.obtenerDispositivos();

        DefaultTableModel modelo = (DefaultTableModel) tblDispositivos.getModel();
        modelo.setRowCount(0);

        for (Dispositivo dispositivo : dispositivos) {
            modelo.addRow(new Object[] { dispositivo.getNombre(), dispositivo.getLocalizacion(), dispositivo.getIp(), dispositivo.getDireccionMac()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDispositivos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Dispositivo - Listar");

        tblDispositivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Localización", "Dirección IP", "Dirección MAC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDispositivos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDispositivos;
    // End of variables declaration//GEN-END:variables
}
