package co.diseno.interfaces.vistas;

import co.diseno.interfaces.controladores.ControladorFactory;
import co.diseno.interfaces.controladores.PrincipalControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author johno
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final int SALIDA_SATISFACTORIA = 0;
    private PrincipalControlador principalControlador;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        principalControlador = (PrincipalControlador) ControladorFactory.getControlador("principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnPrincipal = new javax.swing.JDesktopPane();
        mbrPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnuDispositivos = new javax.swing.JMenu();
        mniDispositivoCrear = new javax.swing.JMenuItem();
        mniDispositivoListar = new javax.swing.JMenuItem();
        mniDispositivoBuscar = new javax.swing.JMenuItem();
        mniDispositivoActualizar = new javax.swing.JMenuItem();
        mniDispositivoEliminar = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mniAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout dpnPrincipalLayout = new javax.swing.GroupLayout(dpnPrincipal);
        dpnPrincipal.setLayout(dpnPrincipalLayout);
        dpnPrincipalLayout.setHorizontalGroup(
            dpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        dpnPrincipalLayout.setVerticalGroup(
            dpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        getContentPane().add(dpnPrincipal, java.awt.BorderLayout.CENTER);

        mnuArchivo.setMnemonic('A');
        mnuArchivo.setText("Archivo");

        mniSalir.setMnemonic('S');
        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mniSalir);

        mbrPrincipal.add(mnuArchivo);

        mnuDispositivos.setMnemonic('O');
        mnuDispositivos.setText("Dispositivos");
        mnuDispositivos.setToolTipText("");

        mniDispositivoCrear.setText("Crear");
        mniDispositivoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDispositivoCrearActionPerformed(evt);
            }
        });
        mnuDispositivos.add(mniDispositivoCrear);

        mniDispositivoListar.setText("Listar");
        mniDispositivoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDispositivoListarActionPerformed(evt);
            }
        });
        mnuDispositivos.add(mniDispositivoListar);

        mniDispositivoBuscar.setText("Buscar");
        mniDispositivoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDispositivoBuscarActionPerformed(evt);
            }
        });
        mnuDispositivos.add(mniDispositivoBuscar);

        mniDispositivoActualizar.setText("Actualizar");
        mniDispositivoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDispositivoActualizarActionPerformed(evt);
            }
        });
        mnuDispositivos.add(mniDispositivoActualizar);

        mniDispositivoEliminar.setText("Eliminar");
        mniDispositivoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDispositivoEliminarActionPerformed(evt);
            }
        });
        mnuDispositivos.add(mniDispositivoEliminar);

        mbrPrincipal.add(mnuDispositivos);

        mnuAyuda.setMnemonic('u');
        mnuAyuda.setText("Ayuda");

        mniAcercaDe.setText("Acerca de...");
        mniAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mniAcercaDe);

        mbrPrincipal.add(mnuAyuda);

        setJMenuBar(mbrPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDispositivoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDispositivoEliminarActionPerformed
        DispositivoEliminarFrame dispositivoEliminarFrame = new DispositivoEliminarFrame(principalControlador);
        dpnPrincipal.add(dispositivoEliminarFrame);
        dispositivoEliminarFrame.setVisible(true);
    }//GEN-LAST:event_mniDispositivoEliminarActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniSalirActionPerformed
        System.exit(SALIDA_SATISFACTORIA);
    }// GEN-LAST:event_mniSalirActionPerformed

    private void mniAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por: Gabriel", "Acerca de...",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_mniAcercaDeActionPerformed

    private void mniDispositivoCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniDispositivoCrearActionPerformed
        DispositivoCrearFrame dispositivoCrearFrame = new DispositivoCrearFrame(principalControlador);
        dpnPrincipal.add(dispositivoCrearFrame);
        dispositivoCrearFrame.setVisible(true);
    }// GEN-LAST:event_mniDispositivoCrearActionPerformed

    private void mniDispositivoListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniDispositivoListarActionPerformed
        DispositivoListarFrame dispositivoListarFrame = new DispositivoListarFrame(principalControlador);
        dpnPrincipal.add(dispositivoListarFrame);
        dispositivoListarFrame.setVisible(true);
    }// GEN-LAST:event_mniDispositivoListarActionPerformed

    private void mniDispositivoBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniDispositivoBuscarActionPerformed
        DispositivoBuscarFrame dispositivoBuscarFrame = new DispositivoBuscarFrame(principalControlador);
        dpnPrincipal.add(dispositivoBuscarFrame);
        dispositivoBuscarFrame.setVisible(true);
    }// GEN-LAST:event_mniDispositivoBuscarActionPerformed

    private void mniDispositivoActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniDispositivoActualizarActionPerformed
        DispositivoActualizarFrame dispositivoActualizarFrame = new DispositivoActualizarFrame(principalControlador);
        dpnPrincipal.add(dispositivoActualizarFrame);
        dispositivoActualizarFrame.setVisible(true);
    }// GEN-LAST:event_mniDispositivoActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnPrincipal;
    private javax.swing.JMenuBar mbrPrincipal;
    private javax.swing.JMenuItem mniAcercaDe;
    private javax.swing.JMenuItem mniDispositivoActualizar;
    private javax.swing.JMenuItem mniDispositivoBuscar;
    private javax.swing.JMenuItem mniDispositivoCrear;
    private javax.swing.JMenuItem mniDispositivoEliminar;
    private javax.swing.JMenuItem mniDispositivoListar;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuDispositivos;
    // End of variables declaration//GEN-END:variables
}
